---
#- name: Install Gdebi
#  apt: name=gdebi

- name: Check the newest version of RStudio
  uri: url=http://download2.rstudio.org/current.ver return_content=yes
  register: rstudio_version
  become: no

- name: Get the archive of RStudio Server
  apt: deb=http://download2.rstudio.org/server/bionic/amd64/rstudio-server-{{ rstudio_version.content.split("-")[0] }}-amd64.deb
  become: yes

#- name: Install RStudio Server
#  command: /usr/bin/gdebi --non-interactive /tmp/rstudio.deb
